

---


Гринюк Андрій Валерійович



---


ФІТ 4-5

---


Лабораторна робота №1

---


Варіант №5

---



In [1]:
# 1 Створіть одновимірний масив (вектор) зі зворотнім порядком перших 10 натуральних чисел та виведіть його значення.

import numpy as np

n = 10
vector = list(range(n, 0, -1))
print(vector)



ModuleNotFoundError: No module named 'numpy'

In [ ]:
# 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю чисел, де кожне наступне число менше попереднього на 3, та виведіть його значення.

matrix = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

start_value = 96

for i in range(3):
    for j in range(3):
        matrix[i][j] = start_value
        start_value -= 3

for row in matrix:
    print(row)

[96, 93, 90]
[87, 84, 81]
[78, 75, 72]


In [ ]:
# 3 Створіть масив розміром 8x8, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.

matrix = np.random.rand(8, 8)

print(matrix)

[[5.55068768e-01 7.16521689e-01 9.95513229e-01 3.98918358e-01
  9.17291036e-01 3.20946681e-02 1.18890866e-01 8.66211840e-01]
 [8.88842684e-01 3.11769372e-01 7.84148357e-01 3.43558371e-02
  3.39754596e-02 1.11251324e-01 3.42764130e-01 5.56122244e-01]
 [3.07369579e-02 3.56568745e-01 8.85080324e-01 2.71146050e-01
  3.02986808e-01 1.66200949e-01 9.56523174e-01 5.28915934e-01]
 [6.88743928e-01 1.76876771e-01 4.64652498e-01 7.74655221e-01
  3.59432240e-04 9.96119321e-01 3.84791511e-01 8.20246811e-01]
 [1.71850519e-01 1.66780780e-01 1.41373789e-01 7.63378907e-01
  2.25845732e-01 1.40789253e-01 4.70044696e-01 9.24595345e-02]
 [9.72206964e-01 4.55734355e-01 3.14462218e-01 8.20542299e-01
  6.39722111e-01 3.33220757e-01 8.57463460e-01 5.31905009e-01]
 [8.38001601e-01 5.12861915e-02 1.55583610e-01 9.85259092e-02
  6.29643670e-01 7.08833008e-01 5.12938531e-01 9.54238748e-01]
 [2.58200624e-01 4.94664354e-01 2.76781070e-01 9.86582184e-01
  1.24176352e-01 2.16379384e-02 2.67814816e-01 5.65036774e-01]]

In [ ]:
# 4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть добуток всіх елементів.

matrix = np.random.rand(3, 3)

print("Матриця:")
print(matrix)

product = np.prod(matrix)

print("Добуток елементів:", product)

Матриця:
[[0.87823719 0.24922131 0.39645078]
 [0.79795525 0.89357486 0.59353382]
 [0.25970151 0.45834221 0.59220028]]
Добуток елементів: 0.0025886548945022905


In [ ]:
# 5 Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в
# діапазоні від -20 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

array1 = np.random.randint(-20, 21, 6)
array2 = np.random.randint(-20, 21, 6)

print("Перший масив:", array1)
print("Другий масив:", array2)

sum = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Результат додавання:", sum)
print("Результат віднімання:", subtraction)
print("Результат множення:", multiplication)

Перший масив: [ 15  -3 -11 -18  -7  10]
Другий масив: [ 20   6  -3   3 -16 -19]
Результат додавання: [ 35   3 -14 -15 -23  -9]
Результат віднімання: [ -5  -9  -8 -21   9  29]
Результат множення: [ 300  -18   33  -54  112 -190]


In [ ]:
# 6 Створіть два вектори розміром 8, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

vector1 = np.random.randint(-100, 101, 8)
vector2 = np.random.randint(-100, 101, 8)

print("Перший вектор:", vector1)
print("Другий вектор:", vector2)

dot = np.dot(vector1, vector2)

print("Скалярний добуток:", dot)

Перший вектор: [ 73  51  82 -19  29  59  20  41]
Другий вектор: [-55  39 -87 -52 -30 -11  95 -52]
Скалярний добуток: -9923


In [ ]:
# 7 Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

matrix1 = np.random.randint(1, 9, size=(3, 2))
matrix2 = np.random.randint(1, 9, size=(2, 2))

print("Перша матриця:")
print(matrix1)

print("Друга матриця:")
print(matrix2)

result_matrix = np.dot(matrix1, matrix2)

print("Результат множення:")
print(result_matrix)

Перша матриця:
[[1 8]
 [2 2]
 [2 1]]
Друга матриця:
[[5 2]
 [1 4]]
Результат перемноження:
[[13 34]
 [12 12]
 [11  8]]


In [ ]:
# 8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix = np.random.randint(1, 11, size=(2, 2))

print("Початкова матриця:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці, оскільки її детермінант дорівнює нулю.")

Початкова матриця:
[[ 3  6]
 [10 10]]
Обернена матриця:
[[-0.33333333  0.2       ]
 [ 0.33333333 -0.1       ]]


In [ ]:
# 9 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.


matrix = np.random.randint(0, 2, size=(3, 3))

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("Транспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[1 0 1]
 [0 0 0]
 [1 1 1]]
Транспонована матриця:
[[1 0 1]
 [0 0 1]
 [1 0 1]]


In [ ]:
# 10	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток вектора на матрицю.

matrix = np.random.rand(3, 4)

print("Початкова матриця:")
print(matrix)

vector = np.random.randint(1, 11, 4)

print("Вектор:")
print(vector)

product = np.dot(matrix, vector)

print("Добуток матриці на вектор:")
print(product)

Початкова матриця:
[[6.57786453e-01 6.88845981e-04 6.72798004e-01 3.45367564e-01]
 [7.90843964e-01 1.73854507e-01 9.00345534e-01 7.64591749e-01]
 [7.82722272e-01 8.41293928e-01 3.70363071e-01 8.32233877e-01]]
Вектор:
[9 1 3 4]
Добуток матриці на вектор:
[ 9.32063119 13.05085378 12.3258191 ]


In [ ]:
# 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму добутків елементів кожного рядка матриці на відповідний елемент вектору.

matrix = np.random.randint(1, 11, size=(2, 3))

print("Початкова матриця:")
print(matrix)

vector = np.random.randint(1, 11, 3)

print("Вектор:")
print(vector)

result = np.sum(matrix * vector, axis=1)

print("Результат:")
print(result)

Початкова матриця:
[[8 2 6]
 [9 9 4]]
Вектор:
[2 2 6]
Результат:
[56 60]


In [ ]:
# 12 Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів першої матриці.

matrix1 = np.random.randint(1, 11, size=(6, 6))
matrix2 = np.random.randint(1, 11, size=(6, 6))

sum_matrix1 = np.sum(matrix1)

print("Сума елементів першої матриці:", sum_matrix1)

print("Перша матриця:")
print(matrix1)

print("Друга матриця:")
print(matrix2)

Сума елементів першої матриці: 168
Перша матриця:
[[ 2  2  3 10  4  4]
 [ 4  5  8  7  3  8]
 [ 2  8  5  9  2  1]
 [ 5  8  6  3  2  3]
 [ 2  6  1  2 10  3]
 [ 6  6  3  6  4  5]]
Друга матриця:
[[ 4  1  4  9  3  5]
 [ 7  7  4  6  2  2]
 [ 9 10  4  1  8  1]
 [ 2  8  5  9  1  9]
 [ 7  5  1  4  9  8]
 [ 2  4  6  3  2  8]]


In [ ]:
# 13 Створіть дві матриці розміром 6x6, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів.


matrix1 = np.random.rand(6, 6)
matrix2 = np.random.rand(6, 6)

difference_matrix = matrix1 - matrix2

print("Різниця елементів матриць:")
print(difference_matrix)

Різниця елементів матриць:
[[ 0.49250377 -0.14936029 -0.18135328 -0.31029803 -0.24342037  0.43673742]
 [-0.18991088  0.20666036 -0.3223368   0.11050471  0.91862822  0.30464433]
 [-0.55117116 -0.13039949 -0.20312646 -0.56502239  0.05932547 -0.17198283]
 [ 0.01306769 -0.49330131  0.19200982 -0.4468191   0.59210934 -0.25787831]
 [ 0.09457541  0.54945024 -0.15767108  0.54339266 -0.87593372  0.17377569]
 [-0.29615864  0.33479939  0.46577092 -0.04120116  0.13888308 -0.70981957]]


In [ ]:
# 14 Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть добуток елементів матриці.

matrix = np.random.uniform(-10, 10, size=(9, 9))

product = np.prod(matrix)

print("Добуток елементів матриці:")
print(product)

Добуток елементів матриці:
8.273883548451385e+42


In [ ]:
# 15 Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні
# від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у кожному рядку матриці.

matrix = np.random.rand(7, 7)

max_in_rows = np.max(matrix, axis=1)

print("Вектор з найбільшими елементами в кожному рядку:")
print(max_in_rows)

Вектор з найбільшими елементами в кожному рядку:
[0.89383274 0.9050895  0.93127844 0.8466159  0.87641604 0.85964941
 0.94062601]
